### ISSUE TITLE
Rearrange positive and negative in an array

### ISSUE THREAD

**Issue by mr-professor4569** [mr-professor4569/Data_Structures#24]

**Comment by aayushi02agarwal** [comment]
I want to do it in cpp. Please assign it to me.

**Comment by mr-professor4569** [comment]
@aayushi02agarwal sorry to say but i have merged the pr of @shudhanshu03 . Its okay , make a pr of any algorithm or any conceptual problem solution in c++. I will surely merged it.

**Comment by shudhanshu03** [comment]
@aayushi02agarwal Try to go for algorithms , there are many algo which u can contribute here.
